### ISSUE TITLE
Discounted Products

### ISSUE THREAD

**Issue by khrizzcristian** [vtex-apps/search-result#456]
Is there any way I can display only discounted products?

Thank you.

**Comment by chrsmutti** [comment]
Hey @khrizzcristian, the issue is a bit old, but I'll reply to it either way for documentation purposes.

When using the Intelligent Search variant, a filter called `Promotion` can be used to filter only "discounted products" as you mentioned. Just make sure it's not on the `Hide Facets` configuration on Admin, and it should be good to go!

![image](https://user-images.githubusercontent.com/34144667/113186571-3927e980-922e-11eb-9722-5bdf47733b42.png)
